name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Run unit tests
      run: cargo test --lib

    - name: Run BDD tests
      run: cargo test --test arithmetic

    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Check code coverage
      run: cargo tarpaulin --ignore-tests --fail-under 95
